image: node:alpine

before_script:
  - apk update
  - apk add zip
  - npm install @prantlf/jsonlint -g

stages:
  - test
  - build

test:
  stage: test
  script:
    - jsonlint -q --enforce-double-quotes dnd5e_pt-BR/

build:
  stage: build
  script:
    - zip dnd5e_pt-BR.zip -r dnd5e_pt-BR
  artifacts:
    expire_in: never
    name: dnd5e_pt-BR
    when: on_success
    paths:
      - dnd5e_pt-BR.zip
  when: on_success
  only:
    - tags
