image: node:14-alpine

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^chore\(release\).*/ || $CI_COMMIT_TAG
      when: never
    - when: always

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pnpm-store

before_script:
  - apk update
  - apk add zip curl wget git openssh-client
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add -
  - pnpm config set store-dir .pnpm-store
  - pnpm set verify-store-integrity false
  - pnpm install

stages:
  - test
  - build
  - release

jsonlint:
  stage: test
  script:
    - pnpx jsonlint -q --enforce-double-quotes dnd5e_pt-BR lang

semistandard:
  stage: test
  script:
    - pnpx semistandard

publish:
  stage: release
  script:
    - pnpx semantic-release
  artifacts:
    name: dnd5e_pt-BR
    when: on_success
    paths:
      - dnd5e_pt-BR.zip
  rules:
      - if: $CI_COMMIT_BRANCH =~ /^(master|main|beta)/ && $CI_PIPELINE_SOURCE != 'schedule'
